spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      groupId: product-event-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.sourav.dto